config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :ad_crawling_dbs
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root  "ad_crawling_dbs#index"
end

app/models/ad_crawling_db.rb
class AdCrawlingDb < ApplicationRecord
	validates_uniqueness_of :title
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/ad_crawling_dbs_controller.rb
class AdCrawlingDbsController < ApplicationController
  before_action :set_ad_crawling_db, only: [:show, :edit, :update, :destroy]

  # GET /ad_crawling_dbs
  # GET /ad_crawling_dbs.json
  def index
    @ad_crawling_dbs = AdCrawlingDb.all
  end

  # GET /ad_crawling_dbs/1
  # GET /ad_crawling_dbs/1.json
  def show
  end

  # GET /ad_crawling_dbs/new
  def new
    @ad_crawling_db = AdCrawlingDb.new
  end

  # GET /ad_crawling_dbs/1/edit
  def edit
  end

  # POST /ad_crawling_dbs
  # POST /ad_crawling_dbs.json
  def create
    @ad_crawling_db = AdCrawlingDb.new(ad_crawling_db_params)

    respond_to do |format|
      if @ad_crawling_db.save
        format.html { redirect_to @ad_crawling_db, notice: 'Ad crawling db was successfully created.' }
        format.json { render :show, status: :created, location: @ad_crawling_db }
      else
        format.html { render :new }
        format.json { render json: @ad_crawling_db.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ad_crawling_dbs/1
  # PATCH/PUT /ad_crawling_dbs/1.json
  def update
    respond_to do |format|
      if @ad_crawling_db.update(ad_crawling_db_params)
        format.html { redirect_to @ad_crawling_db, notice: 'Ad crawling db was successfully updated.' }
        format.json { render :show, status: :ok, location: @ad_crawling_db }
      else
        format.html { render :edit }
        format.json { render json: @ad_crawling_db.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ad_crawling_dbs/1
  # DELETE /ad_crawling_dbs/1.json
  def destroy
    @ad_crawling_db.destroy
    respond_to do |format|
      format.html { redirect_to ad_crawling_dbs_url, notice: 'Ad crawling db was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ad_crawling_db
      @ad_crawling_db = AdCrawlingDb.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ad_crawling_db_params
      params.require(:ad_crawling_db).permit(:title, :ad_url, :company_name, :img_url, :web_url)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/ad_crawling_dbs_helper.rb
module AdCrawlingDbsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/ad_crawling_dbs/_form.html.erb
<%= form_with(model: ad_crawling_db, local: true) do |form| %>
  <% if ad_crawling_db.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ad_crawling_db.errors.count, "error") %> prohibited this ad_crawling_db from being saved:</h2>

      <ul>
        <% ad_crawling_db.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :ad_url %>
    <%= form.text_field :ad_url %>
  </div>

  <div class="field">
    <%= form.label :company_name %>
    <%= form.text_field :company_name %>
  </div>

  <div class="field">
    <%= form.label :img_url %>
    <%= form.text_field :img_url %>
  </div>

  <div class="field">
    <%= form.label :web_url %>
    <%= form.text_field :web_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ad_crawling_dbs/edit.html.erb
<h1>Editing Ad Crawling Db</h1>

<%= render 'form', ad_crawling_db: @ad_crawling_db %>

<%= link_to 'Show', @ad_crawling_db %> |
<%= link_to 'Back', ad_crawling_dbs_path %>

app/views/ad_crawling_dbs/index.html.erb
<p id="notice"><%= notice %></p>

<table class="content_per">
  <thead>
    <tr>
      <th>Id</th>
      <th>Title</th>
      <th>Link</th>
      <th>Imglink</th>
    </tr>
  </thead>

  <tbody>
    <% @ad_crawling_dbs.each do |content| %>
      <tr>
        <td class="table_num"> <%= content.id %></td>
        <td class="table_left"><%= link_to content.title, "#{content.ad_url}" %></td>
        <td class="table_center"><a href="<%= content.ad_url %>">Link</a></td>
        <td class="table_right"><img class="img_table" src="<%= content.img_url %>"></td>
      </tr>
    <% end %>
  </tbody>
</table>


<script type="text/javascript">
  setInterval("my_function();",900000); 
 
    function my_function(){
        window.location.href = "/";
    }
</script>

<br>

app/views/ad_crawling_dbs/new.html.erb
<h1>New Ad Crawling Db</h1>

<%= render 'form', ad_crawling_db: @ad_crawling_db %>

<%= link_to 'Back', ad_crawling_dbs_path %>

app/views/ad_crawling_dbs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @ad_crawling_db.title %>
</p>

<p>
  <strong>Ad url:</strong>
  <%= @ad_crawling_db.ad_url %>
</p>

<p>
  <strong>Company name:</strong>
  <%= @ad_crawling_db.company_name %>
</p>

<p>
  <strong>Img url:</strong>
  <%= @ad_crawling_db.img_url %>
</p>

<p>
  <strong>Web url:</strong>
  <%= @ad_crawling_db.web_url %>
</p>

<%= link_to 'Edit', edit_ad_crawling_db_path(@ad_crawling_db) %> |
<%= link_to 'Back', ad_crawling_dbs_path %>

app/views/layouts/_footer.html.erb
<footer class="page-footer">

  <div class="container-fluid text-center text-md-left">

    <div class="row">

      <div class="col-md-6 mt-md-0 mt-3">

		<div class="paginate-pos">

		</div>

      </div>

      <hr class="clearfix w-100 d-md-none pb-3">


  </div>



  <div class="footer-copyright text-center py-3">© 2020 Copyright:
    <a> Aidos </a>
  </div>


</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BulletinTraining</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <%= link_to "AdForFullout" , root_path, class:'navbar-brand'%>

        </div>

        <ul class="nav navbar-nav">

            <li> <%= link_to "Search", root_path %></li>
            <li> <%= link_to "Categories", root_path %></li>
        <div class="navbar-user navbar-right">
            <div class="navbar-text nvabar">

              <p> Current User </p>
              
            </div>
            <div class="navbar-right navbar-btn navbar-log" >
                  <li> <%= link_to "Log in", root_path %> </li>
                  <li> <%= link_to "Sign Up", root_path %></li>
            </div>
        </div>
        </ul>

      </div>
    </div>
    <div class="container">
      <p class="notice"><%= flash.now[notice] %></p>
      <p class="alert"><%= flash.now[alert] %></p>
      <div class="crawl-btn">
        <p>
          <%= form_tag root_path, :method => 'get' do %>
              <label for="search_range">How many Reloads will we use? </label>
              <input type="number" name="search_range" id="search_range" value="" size="40"/>
              <input type="submit" name="commit" value="Search"/> 
           <% end %>
        </p>
      </div>
      <%= yield %>
      <%= render "layouts/footer" %>



    </div>  
  </body>
</html>